project:
  name: quickstart-aerospike
  owner: quickstart-eng@amazon.com
  package_lambda: true
  shorten_stack_name: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  regions:
  - us-east-1
  template: templates/aerospike-cluster-entrypoint-new-vpc.template.yaml
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    NumberOfAZs: 2
    AccessCIDR: --overridden--
    KeyPairName: --overridden--
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: quickstart-aerospike/
tests:
  aerospike-single-region:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
    regions:
    - eu-west-1
  aerospike-multi-region:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      NumberOfAZs: 3
    regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - ca-central-1
    - eu-central-1
    - ap-southeast-1
    - sa-east-1
