// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading
After the AWS CloudFormation stack is complete, test the deployment by checking whether the instances were properly enrolled with your {partner-product-short-name} project.

To validate the system and verify the system configuration, follow these steps:

. From the bastion host, use SSH to log in to one of the Aerospike instances created by Quick Start template. Use SSH key forwarding for security purposes. For more info on SSH key forwarding, see https://docs.github.com/en/developers/overview/using-ssh-agent-forwarding[Using SSH agent forwarding^].
+
----
$ ssh ec2-user@<aerospike-instance>
----

. Verify cluster information using `asadm` command. More information, see https://docs.aerospike.com/docs/tools/asadm/[Aerospike Admin (asadm)^]. A two-node cluster output looks like this:
+
----
$ asadm
Seed:        [('127.0.0.1', 3000, None)]
Config_file: /home/ec2-user/.aerospike/astools.conf, /etc/aerospike/astools.conf
Aerospike Interactive Shell, version 2.0.1

Found 2 nodes
Online:  10.0.3.128:3000, 10.0.35.3:3000

Admin> summary
Cluster  (Migrations in Progress)
=================================

   1.   Server Version     :  E-5.5.0.4
   2.   OS Version         :  Amazon Linux 2 (4.14.231-173.361.amzn2.x86_64)
   3.   Cluster Size       :  2
   4.   Devices            :  Total 0, per-node 0
   5.   Memory             :  Total 16.000 GB, 0.00% used (0.000 B), 100.00% available (16.000 GB)
   6.   Disk               :  Total 0.000 B, 0.00% used (0.000 B), 0.00% available contiguous space (0.000 B)
   7.   Usage (Unique Data):  None
   8.   Active Namespaces  :  0 of 2
   9.   Features           :


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Namespaces~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Namespace|~~~Devices~~~~|~~~~~~~~Memory~~~~~~~|~~~~~~~~~Disk~~~~~~~~|Replication| Master|~~~~~~Usage~~~~~~~
         |Total|Per-Node|   Total|Used%|Avail%|   Total|Used%|Avail%|    Factors|Objects|~~(Unique-Data)~~~
         |     |        |        |     |      |        |     |      |           |       |In-Memory| On-Disk
bar      |    0|       0|8.000 GB|    0|   100|0.000 B |    0|     0|          2|0.000  | 0.000 B |0.000 B
test     |    0|       0|8.000 GB|    0|   100|0.000 B |    0|     0|          2|0.000  | 0.000 B |0.000 B
Number of rows: 2

----
+

. Insert record using https://docs.aerospike.com/docs/tools/aql/[aql^]. The following commands insert a record in test namespace. Replace *foo* with the set name and *bar* with the bin name.
+
----
$ aql
Seed:         127.0.0.1
User:         None
Config File:  /etc/aerospike/astools.conf /home/ec2-user/.aerospike/astools.conf
Aerospike Query Client
Version 5.0.1
C Client Version 4.6.17
Copyright 2012-2020 Aerospike. All rights reserved.

aql> insert into test.foo (PK, bar) values (123, 'you did it!')
OK, 1 record affected.

aql> select * from test.foo
+---------------+
| bar           |
+---------------+
| "you did it!" |
+---------------+
1 row in set (0.036 secs)

OK
----

For more information on testing, see https://docs.aerospike.com/docs/client/java/benchmarks.html[Benchmarks^]. With the benchmark application, you can exercise and demo load on the new Aerospike cluster. 

== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

Follow these best practices: https://docs.aerospike.com/docs/deploy_guides/aws/recommendations/index.html[Aerospike on Amazon EC2 - Recommendations^].

Also set up a backup plan your {partner-product-short-name} data. For details, see https://docs.aerospike.com/docs/deploy_guides/aws/backup/index.html[Backup and Recovery in AWS^].

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

When you run {partner-product-short-name} in production, review and ensure that your security best practices are understood and followed. You'll find some recommended security best practices in https://docs.aerospike.com/docs/deploy_guides/aws/recommendations/index.html[Aerospike on Amazon EC2 - Recommendations^].

== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

After your deployment is up and ready, read and understand the following sections of the Aerospike documentation. Use the navigation panel to open each subsection within these main sections. 

* https://docs.aerospike.com/docs/operations/configure/index.html[Configure Aerospike Database^]
* https://docs.aerospike.com/docs/operations/manage/index.html[Manage^]
* https://docs.aerospike.com/docs/operations/monitor/index.html[Monitoring^]
* https://docs.aerospike.com/docs/operations/troubleshoot/index.html[Troubleshoot^]
* https://docs.aerospike.com/docs/architecture/clients.html[Client Architecture^]
* https://docs.aerospike.com/docs/connect/index.html[Overview of Aerospike Connect^]

For information on the architecture and system, see the Aerospike https://docs.aerospike.com/docs/architecture/index.html[Architecture Overview^] and https://docs.aerospike.com/docs/operations/index.html[System Overview^]

For information on monitoring your stack, see https://docs.aerospike.com/docs/tools/monitorstack/index.html[Overview to the Aerospike Monitoring Stack^].

For information on querying your database, see https://docs.aerospike.com/docs/guide/query.html[Query^]. 

For information on setting up and using connectors to stream data into your new cluster, see https://docs.aerospike.com/docs/connect/index.html[Overview of Aerospike Connect^].
