// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading
After the AWS CloudFormation stack is complete, you can test the deployment by checking whether the instances were properly enrolled with your {partner-product-short-name} project.

To validate the system and verify the system configuration, follow these steps: 
1. From bastion host, use SSH to log in to one of the aerospike instance created by Quick Start template. It's recommended to use ssh key forwarding for security purpose. More info on ssh key forwarding can be found https://docs.github.com/en/developers/overview/using-ssh-agent-forwarding[here]
----
$ ssh ec2-user@<aerospike-instance>
----

2. Verify cluster information using `asadm` command. More information about asadm can be found https://docs.aerospike.com/docs/tools/asadm/[here]. For two node cluster output should look like this : 
----
$ asadm
Seed:        [('127.0.0.1', 3000, None)]
Config_file: /home/ec2-user/.aerospike/astools.conf, /etc/aerospike/astools.conf
Aerospike Interactive Shell, version 2.0.1

Found 2 nodes
Online:  10.0.3.128:3000, 10.0.35.3:3000

Admin> summary
Cluster  (Migrations in Progress)
=================================

   1.   Server Version     :  E-5.5.0.4
   2.   OS Version         :  Amazon Linux 2 (4.14.231-173.361.amzn2.x86_64)
   3.   Cluster Size       :  2
   4.   Devices            :  Total 0, per-node 0
   5.   Memory             :  Total 16.000 GB, 0.00% used (0.000 B), 100.00% available (16.000 GB)
   6.   Disk               :  Total 0.000 B, 0.00% used (0.000 B), 0.00% available contiguous space (0.000 B)
   7.   Usage (Unique Data):  None
   8.   Active Namespaces  :  0 of 2
   9.   Features           :


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Namespaces~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Namespace|~~~Devices~~~~|~~~~~~~~Memory~~~~~~~|~~~~~~~~~Disk~~~~~~~~|Replication| Master|~~~~~~Usage~~~~~~~
         |Total|Per-Node|   Total|Used%|Avail%|   Total|Used%|Avail%|    Factors|Objects|~~(Unique-Data)~~~
         |     |        |        |     |      |        |     |      |           |       |In-Memory| On-Disk
bar      |    0|       0|8.000 GB|    0|   100|0.000 B |    0|     0|          2|0.000  | 0.000 B |0.000 B
test     |    0|       0|8.000 GB|    0|   100|0.000 B |    0|     0|          2|0.000  | 0.000 B |0.000 B
Number of rows: 2

----

3. Insert record using https://docs.aerospike.com/docs/tools/aql/[aql]. Following commands inserts a record in test namespace with foo as set name and bar as bin name:
----
$ aql
Seed:         127.0.0.1
User:         None
Config File:  /etc/aerospike/astools.conf /home/ec2-user/.aerospike/astools.conf
Aerospike Query Client
Version 5.0.1
C Client Version 4.6.17
Copyright 2012-2020 Aerospike. All rights reserved.

aql> insert into test.foo (PK, bar) values (123, 'you did it!')
OK, 1 record affected.

aql> select * from test.bar
0 rows in set (0.023 secs)

OK

aql> select * from test.foo
+---------------+
| bar           |
+---------------+
| "you did it!" |
+---------------+
1 row in set (0.036 secs)

OK
----

For additional information on testing you can use the https://docs.aerospike.com/docs/client/java/benchmarks.html[benchmark] tool to exercise and demo load on the new Aerospike cluster, otherwise you can check out https://docs.aerospike.com/docs/guide/query.html[Query] for information on querying the {partner-product-short-name} and https://docs.aerospike.com/docs/connect/index.html[here] to checkout {partner-product-short-name} how to set up and use connectors to stream data into your new cluster.

== Post-deployment steps
// If post-deployment steps are required, add them here. If not, remove the heading

After your deployment is up and ready, you can read more on 

 - https://docs.aerospike.com/docs/operations/configure/index.html[Configuring]
 - https://docs.aerospike.com/docs/operations/manage/index.html[Managing]
 - https://docs.aerospike.com/docs/operations/monitor/index.html[Monitoring]
 - https://docs.aerospike.com/docs/operations/troubleshoot/index.html[Troubleshooting]
 - https://docs.aerospike.com/docs/architecture/clients.html[Clients]
 - https://docs.aerospike.com/docs/connect/index.html[Connectors]


== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

https://docs.aerospike.com/docs/deploy_guides/aws/recommendations/index.html[best practices] contains a lot of information on best practices for running {partner-product-short-name} in AWS.

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

When running {partner-product-short-name} in production it's important to review and ensure security best practices are understood and followed.

When it comes to backing up and restoring your data, There are many ways to accomplish this task depending on your needs. Check out the {partner-product-short-name} AWS https://docs.aerospike.com/docs/deploy_guides/aws/backup/index.html[docs] for more information to empowering what way is best for you on AWS.

Check out https://docs.aerospike.com/docs/deploy_guides/aws/recommendations/index.html[best practices] for security and other best practices when running {partner-product-short-name} in production.

== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

Additional information can be found on the Aerospike https://docs.aerospike.com/docs/architecture/index.html[Architecture] as well as extra information on https://docs.aerospike.com/docs/operations/index.html[operations]

The ability to monitor the stack is provided by our https://docs.aerospike.com/docs/tools/monitorstack/index.html[Monitoring Stack]